[build]
builder = "nixpacks"

[deploy]
startCommand = "echo 'Please use service-specific railway.json files'"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
[environments.preview]
