[build]
builder = "nixpacks"

[deploy]
"startCommand": "cd apps/api && pnpm start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
[environments.preview]
